# Prettier Configuration
# Professional code formatting for TakipUI

# Basic Options
printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: "as-needed"
trailingComma: "es5"

# JSX Options
jsxSingleQuote: true
jsxBracketSameLine: false

# Other Options
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
rangeStart: 0
requirePragma: false
insertPragma: false
proseWrap: "preserve"
htmlWhitespaceSensitivity: "css"
vueIndentScriptAndStyle: false
endOfLine: "lf"
embeddedLanguageFormatting: "auto"

# Override specific file types
overrides:
  - files: "*.json"
    options:
      printWidth: 120
      tabWidth: 2
  
  - files: "*.md"
    options:
      printWidth: 80
      proseWrap: "always"
  
  - files: "*.html"
    options:
      printWidth: 120
      htmlWhitespaceSensitivity: "ignore"
  
  - files: "*.css"
    options:
      printWidth: 120
      singleQuote: false